### ISSUE TITLE
EventEmitter memory leak detected. 11 pull_request listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by mlutfy** [civicrm/probot-civicrm#6]
```
Oct 31 10:21:22 botdylan systemd[1]: Started Probot for CiviCRM.
Oct 31 10:21:22 botdylan npm[2444]: > probot-civicrm@1.0.0 start /home/co/probot-civicrm
Oct 31 10:21:22 botdylan npm[2444]: > probot run ./index.js
Oct 31 10:21:23 botdylan npm[2444]: warning: possible EventEmitter memory leak detected. 11 pull_request listeners added. Use emitter.setMaxListeners() to increase limit.
Oct 31 10:21:23 botdylan npm[2444]: Trace
Oct 31 10:21:23 botdylan npm[2444]:     at _addListener (/home/co/probot-civicrm/node_modules/promise-events/emitter.js:413:17)
Oct 31 10:21:23 botdylan npm[2444]:     at EventEmitter.addListener (/home/co/probot-civicrm/node_modules/promise-events/emitter.js:180:12)
Oct 31 10:21:23 botdylan npm[2444]:     at Robot.on (/home/co/probot-civicrm/node_modules/probot/lib/robot.js:100:24)
Oct 31 10:21:23 botdylan npm[2444]:     at event.forEach.e (/home/co/probot-civicrm/node_modules/probot/lib/robot.js:94:31)
Oct 31 10:21:23 botdylan npm[2444]:     at Array.forEach (<anonymous>)
Oct 31 10:21:23 botdylan npm[2444]:     at Robot.on (/home/co/probot-civicrm/node_modules/probot/lib/robot.js:94:13)
Oct 31 10:21:23 botdylan npm[2444]:     at module.exports (/home/co/probot-civicrm/node_modules/probot-commands/index.js:36:9)
Oct 31 10:21:23 botdylan npm[2444]:     at module.exports (/home/co/probot-civicrm/lib/extpr-plugin.js:33:3)
Oct 31 10:21:23 botdylan npm[2444]:     at module.exports (/home/co/probot-civicrm/index.js:11:32)
Oct 31 10:21:23 botdylan npm[2444]:     at load (/home/co/probot-civicrm/node_modules/probot/lib/index.js:81:5)
Oct 31 10:21:23 botdylan npm[2444]:     at apps.concat.forEach.app (/home/co/probot-civicrm/node_modules/probot/lib/index.js:92:45)
Oct 31 10:21:23 botdylan npm[2444]:     at Array.forEach (<anonymous>)
Oct 31 10:21:23 botdylan npm[2444]:     at Object.setup (/home/co/probot-civicrm/node_modules/probot/lib/index.js:92:30)
Oct 31 10:21:23 botdylan npm[2444]:     at pkgConf.then.pkg (/home/co/probot-civicrm/node_modules/probot/bin/probot-run.js:47:10)
```

**Comment by mlutfy** [comment]
I disabled one of the actions for now, `require('./lib/docs_integrate')(robot)`, and the bot started (and docs are on gitlab?)
